### PR TITLE
Cursor handling

### PR DESCRIPTION
**Pull request by rozza**
2 commits.

1st - allows the user to set the cursor batchsize
2nd - ensures partitions can survive cursor timeouts.

### CODE REVIEW

**Comment by rozza** [comment]
Understood, that's why it logs an error message, would you prefer it to be a setting that controls the regeneration? I don't think that actually achieve anything - users hitting this error would still blame the connector for breaking the Spark Job and then set the setting.

Other than $skip there is no other way to forward to the current location - as a pipeline is transformative we can't change the initial match range.  RDD's should be immutable, then skipping across the bounds of the results of that partition is totally valid.

Regarding changes to the underlying data because of inserts/deletes/updates that issue already exists. Partitioning happens at time x and reading a partition at time y.  Cursors currently would be regenerated as the failed task due to how Spark jobs are retried, however the whole task restarts. 

This change internalizes the retrying process when reading the data, so that when there is inefficient downstream reading of the data (10 minutes between reading more data from a cursor) it doesn't become a fatal failure.

The change is currently being tested on a Snapshot by the user hitting the issue.

**Comment by jyemin** [comment]
I would prefer a setting, yes.  I think it achieves something, in that it provides a workaround to the problem that is not available currently.  In the documentation for it we can clearly state what it's doing and when it's necessary in order to mitigate any blame.

Regarding immutability of RDDs: I've always been curious about that in the context of MongoDB.  Since we don't have global snapshot read support yet, in practice are user's jobs typically running against effectively immutable data, or are they just tolerating some inconsistency in their results?

**Comment by rozza** [comment]
Sounds like a plan - will make it a setting and reinstate the `MongoSparkCursorNotFoundException` to point to the setting.

Snapshot read support wouldn't help - as its multiple cursors over the dataset, called at multiple points in time. So users have to be responsible for the stability of the data when using spark.

**Comment by neverforgit** [comment]
I would really like to use have cursor batchSize setting. 

Regarding immutability and inconsistency, it has not been a big concern for our project. Mongo records data from realtime streams that we are running machine learning models against. We pull the historical data from Mongo and flatten it for training our models nightly. Generally, day to day changes in the stream features are pretty stable, allowing us to grab enough observations with consistent "schemas" to train our models. But the daily training also allows the model to learn or forget features as they come and go over time.

**Comment by rozza** [comment]
Closing - keeping the batchsize setting. But not reconstructing the cursor.

**Pull request closed without merging**
